<a href="https://colab.research.google.com/github/willkwon-math/class-for-deeplearning/blob/master/Pytorch_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch 기본부터 차근차근

이 노트의 목적은 '20. 09. 05.(토)에 한 스터디에서 부족한 부분을 채우기 위함임.

**장점**
- 다양한 라이브러리 제공
- GPU 사용가능








# 기본개념 



## 텐서(Tensor)
$N$개의 배열을 파이토치가 처리하는 기본단위


In [ ]:
!pip install torch
import torch
import numpy

## Torch.nn 라이브러리

여러가지 계산을 포함하고 있는 라이브러리
- Nonlinear Activations
- Convolution Layers
- Linear Layers
- Loss Functions
- Distance Functions

# 코드로 이해하기

## 기본적인 코드

요악
- torch.empty(행,열)  / 초기화되지 않은 행렬을 생성한다.
- torch.zeros(행,열,dtype) / dtype으로 0으로 채워진 행렬을 생성
- torch.tensor([]) / 데이터로부터 tensor를 생성 
- x.size() / 행렬의 크기를 구함.

초기화되지 않은 $5 \times 3$행렬을 생성한다.

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[1.5821e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 5.5117e-36]])


무작위로 초기화된 행렬을 생성한다.

In [ ]:
x=torch.rand(5, 3)
print(x)

tensor([[0.8470, 0.5545, 0.9009],
        [0.1654, 0.2262, 0.0804],
        [0.5215, 0.0306, 0.3924],
        [0.4694, 0.2791, 0.1824],
        [0.9154, 0.0719, 0.2088]])


dtype이 long이고 0으로 채워진 행렬을 생성한다. 

In [ ]:
x=torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 생성한다. 

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


행렬의 크기를 구하는 방법

In [ ]:
x=torch.zeros(5,3,dtype=torch.long)
print(x.size())

torch.Size([5, 3])


자세한 계산들을 여기서 확인가능

https://pytorch.org/docs/stable/torch.html

## torch.nn 라이브러리 


# 예제에서 사용된 것들



## numpy(넘파이)

- Numerical Python의 줄임말
- https://doorbw.tistory.com/171

In [5]:
import numpy as np

data1 = [1,2,3,4,5]
arr1 = np.array(data1)
print(arr1.shape)
arr1

(5,)


array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2.shape)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

연산은 shape이 같을 때 할 수 있음. 
broadcast라는 기능 또한 있음

인덱싱 규칙

In [11]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(arr2[0,0])
print(arr2[3,2])
print(arr2[:,2]) #모든 열의 2번째 요소 꺼내기

1
12
[ 3  6  9 12]


> np.random.normal(mean,standard-deviation,size)

> out : ndarray or scalar

Draw random samples from a normal distribution



In [16]:
a = np.random.normal(0,1,size=(2,4))
a

array([[ 0.52714407,  0.02279393,  0.99861222,  1.05540551],
       [ 0.3675054 , -0.84605962, -0.69975024,  0.60295316]])

numpy.reshape(a, newshape, order='C')[source]
Gives a new shape to an array without changing its data.

In [23]:
a = np.arange(8).reshape((4, 2))
print(a)

print()

a =np.reshape(a, (2, 4))
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1 2 3]
 [4 5 6 7]]


## pytorch 

> torch.from_numpy(ndarray) → Tensor

Creates a Tensor from a numpy.ndarray.

In [ ]:
a = numpy.array([1,2,3])
t = torch.from_numpy(a)
print(t)



t[0]=-1
a
print(a)

tensor([1, 2, 3])
[-1  2  3]


> self.layer



> torch.nn.Linear(in_features, out_features, bias=True)

$ y = xA^T +b $와 같은 함수를 도입. 


https://towardsdatascience.com/how-to-build-your-own-pytorch-neural-network-layer-from-scratch-842144d623f6

In [26]:
import torch
import torch.nn as nn

m = nn.Linear(20,30)
input = torch.randn(128, 20)
output = m(input)
print(output.size())

torch.Size([128, 30])


> class torch.nn.Module

Neural network module의 기본이 되는 class



In [ ]:
class LinearRegressionModel(torch.nn.Module):
  def __init__(self):
    super(LinearRegressionModel, self).__init__() #check
    self.layer = torch.nn.Linear(2,1,bias=True)#???

  def forward(self, inputs):
    outputs = self.layer(inputs)
    return outputs

model = LinearRegressionModel()

print(model.layer.weight.data)
print(model.layer.bias.data)

Q1. 왜 __init__(self) 이 부분이 나타나는가?

A. model = LinearRegressionModel()이 작동할 때 init 파트가 실행된다. initialization을 하는 파트




https://stackoverflow.com/questions/58795601/pytorch-understand-how-nn-module-class-internally-work

Q2. forward 파트는 무엇인가?

forward함수에서는 모델에서 인풋을 어떻게 넣었을 때 아웃풋이 어떻게 될지를 정의한다.  

Hopefully, you use them in the other order - opt.zero_grad(), loss.backward(), opt.step().

- zero_grad clears old gradients from the last step (otherwise you’d just accumulate the gradients from all loss.backward() calls).
- loss.backward() computes the derivative of the loss w.r.t. the parameters (or anything requiring gradients) using backpropagation.
- opt.step() causes the optimizer to take a step based on the gradients of the parameters.
- loss_epoch